# -*- coding: utf-8 -*-
"""Mapa_Colombia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15MrWiIfHuHcQnfMfH6cf6BzAJtiGWKUi

## Importar librerias
"""

import pandas as pd
#import numpy as np
import plotly.graph_objs as go
import plotly.offline as pyo # para exportar en html

"""## Importar json con las ubicaciones por departamento"""

import json
from urllib.request import urlopen
with urlopen('https://gist.githubusercontent.com/john-guerra/43c7656821069d00dcbc/raw/be6a6e239cd5b5b803c6e7c2ec405b793a9064dd/Colombia.geo.json') as response:
    counties = json.load(response)

#counties

"""## Cargar base de datos"""

# Conexión Google Drive

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_excel('/content/drive/MyDrive/0 tutoriales/1 mapa colombia/Base.xlsx')
df

"""## Crear mapa"""

locs = df['Departamento']

for loc in counties['features']:
    loc['id'] = loc['properties']['NOMBRE_DPT']
fig = go.Figure(go.Choroplethmapbox(
                    geojson=counties,
                    locations=locs,
                    z=df['Número'],
                    colorscale='Viridis',
                    colorbar_title="Número"))
fig.update_layout(mapbox_style="carto-positron",
                        mapbox_zoom=3.4,
                        mapbox_center = {"lat": 4.570868, "lon": -74.2973328})
fig.show()

"""## Exportar en html"""

pyo.plot(fig, filename = '/content/drive/MyDrive/0 tutoriales/1 mapa colombia/Mapa_Contagiados.html')